### ISSUE TITLE
009 Documentation

### ISSUE THREAD

**Issue by koukel** [MCCS-Okinawa-Code-Club/foster_club_website#13]
Add HTML comments to the code documenting what different sections are doing.  See https://html.com/tags/comment-tag/#:~:text=An%20HTML%20comment%20begins%20with,is%20rendered%20by%20a%20browser. for examples.

**Comment by harshitasao** [comment]
I will work on it.

**Comment by koukel** [comment]
Awesome, I just assigned you.  Let me know if you need any help or information!

**Comment by harshitasao** [comment]
Sure.

**Comment by PurpleAce88** [comment]
I will do

**Comment by PurpleAce88** [comment]
I have Completed it.
