### ISSUE TITLE
012 Add 1/6 Links

### ISSUE THREAD

**Issue by koukel** [MCCS-Okinawa-Code-Club/foster_club_website#20]
Add the links for the 1/6/22 meeting listed here: https://docs.google.com/spreadsheets/d/1o2_9yuo-8359aqoowmYcdYgL4P54mUuPBUOTLQUZF7Y/edit?usp=sharing

**Comment by PurpleAce88** [comment]
Im doing it now

**Comment by PurpleAce88** [comment]
I did it
